; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32532.0 

	TITLE	D:\my-github\personal-blog-dmytro.zharii.com\articles\2023-06-01-the-value-objects.assets\code-snippets\2023-06-11-the-c-lang-value-object\operation.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_operation_from_string
PUBLIC	_operation_new
PUBLIC	??_C@_03BDGOHNNK@add@				; `string'
PUBLIC	??_C@_03KCMAIMAP@sub@				; `string'
PUBLIC	??_C@_03IMIFIBCN@mul@				; `string'
PUBLIC	??_C@_03FEJMGOGI@div@				; `string'
PUBLIC	??_C@_0CD@EAKMBLEJ@Error?3?5operation?5string?5is?5inva@ ; `string'
PUBLIC	??_C@_0CC@EOBCENKH@Error?3?5operation?5value?5is?5inval@ ; `string'
EXTRN	_malloc:PROC
EXTRN	_strncmp:PROC
EXTRN	_strnlen:PROC
;	COMDAT ??_C@_0CC@EOBCENKH@Error?3?5operation?5value?5is?5inval@
CONST	SEGMENT
??_C@_0CC@EOBCENKH@Error?3?5operation?5value?5is?5inval@ DB 'Error: opera'
	DB	'tion value is invalid', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0CD@EAKMBLEJ@Error?3?5operation?5string?5is?5inva@
CONST	SEGMENT
??_C@_0CD@EAKMBLEJ@Error?3?5operation?5string?5is?5inva@ DB 'Error: opera'
	DB	'tion string is invalid', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_03FEJMGOGI@div@
CONST	SEGMENT
??_C@_03FEJMGOGI@div@ DB 'div', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03IMIFIBCN@mul@
CONST	SEGMENT
??_C@_03IMIFIBCN@mul@ DB 'mul', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03KCMAIMAP@sub@
CONST	SEGMENT
??_C@_03KCMAIMAP@sub@ DB 'sub', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03BDGOHNNK@add@
CONST	SEGMENT
??_C@_03BDGOHNNK@add@ DB 'add', 00H			; `string'
CONST	ENDS
; Function compile flags: /Ogspy
;	COMDAT _operation_new
_TEXT	SEGMENT
_op_type$ = 8						; size = 4
_operation_new PROC					; COMDAT
; File D:\my-github\personal-blog-dmytro.zharii.com\articles\2023-06-01-the-value-objects.assets\code-snippets\2023-06-11-the-c-lang-value-object\operation.c
; Line 29
	push	esi
; Line 30
	push	8
	call	_malloc
	pop	ecx
; Line 32
	mov	ecx, DWORD PTR _op_type$[esp]
	mov	esi, eax
	lea	eax, DWORD PTR [ecx-1]
	cmp	eax, 3
	ja	SHORT $LN4@operation_
; Line 38
	mov	DWORD PTR [esi], ecx
; Line 39
	xor	eax, eax
	jmp	SHORT $LN3@operation_
$LN4@operation_:
; Line 33
	push	8
	call	_malloc
	pop	ecx
; Line 34
	mov	DWORD PTR [eax], 2
; Line 35
	mov	DWORD PTR [eax+4], OFFSET ??_C@_0CC@EOBCENKH@Error?3?5operation?5value?5is?5inval@
$LN3@operation_:
; Line 42
	mov	DWORD PTR [esi+4], eax
	mov	eax, esi
	pop	esi
; Line 43
	ret	0
_operation_new ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT _operation_from_string
_TEXT	SEGMENT
_op_str$ = 8						; size = 4
_operation_from_string PROC				; COMDAT
; File D:\my-github\personal-blog-dmytro.zharii.com\articles\2023-06-01-the-value-objects.assets\code-snippets\2023-06-11-the-c-lang-value-object\operation.c
; Line 5
	push	esi
; Line 11
	mov	esi, DWORD PTR _op_str$[esp]
	push	edi
	push	10					; 0000000aH
	push	esi
	call	_strnlen
	pop	ecx
	pop	ecx
	push	3
	pop	edi
	cmp	eax, edi
	jne	SHORT $LN2@operation_
	push	edi
	push	OFFSET ??_C@_03BDGOHNNK@add@
	push	esi
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN2@operation_
; Line 12
	push	1
$LN20@operation_:
; Line 27
	call	_operation_new
	jmp	$LN19@operation_
$LN2@operation_:
; Line 13
	push	10					; 0000000aH
	push	esi
	call	_strnlen
	pop	ecx
	pop	ecx
	cmp	eax, edi
	jne	SHORT $LN4@operation_
	push	edi
	push	OFFSET ??_C@_03KCMAIMAP@sub@
	push	esi
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN4@operation_
; Line 14
	push	2
	jmp	SHORT $LN20@operation_
$LN4@operation_:
; Line 15
	push	10					; 0000000aH
	push	esi
	call	_strnlen
	pop	ecx
	pop	ecx
	cmp	eax, edi
	jne	SHORT $LN6@operation_
	push	edi
	push	OFFSET ??_C@_03IMIFIBCN@mul@
	push	esi
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN6@operation_
; Line 16
	push	edi
	jmp	SHORT $LN20@operation_
$LN6@operation_:
; Line 17
	push	10					; 0000000aH
	push	esi
	call	_strnlen
	pop	ecx
	pop	ecx
	cmp	eax, edi
	jne	SHORT $LN8@operation_
	push	edi
	push	OFFSET ??_C@_03FEJMGOGI@div@
	push	esi
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN8@operation_
; Line 18
	push	4
	jmp	SHORT $LN20@operation_
$LN8@operation_:
; Line 20
	push	8
	call	_malloc
	mov	esi, eax
; Line 23
	push	8
	mov	DWORD PTR [esi], 1
	mov	DWORD PTR [esi+4], OFFSET ??_C@_0CD@EAKMBLEJ@Error?3?5operation?5string?5is?5inva@
	call	_malloc
	pop	ecx
; Line 24
	mov	DWORD PTR [eax+4], esi
$LN19@operation_:
; Line 27
	pop	ecx
	pop	edi
	pop	esi
	ret	0
_operation_from_string ENDP
_TEXT	ENDS
END
