#+title: Why You Shouldn't Learn Japanese
#+subtitle: japan
#+date: <2013-01-01>
#+language: en

by Ken Seeroi


https://archive.ph/wd0m5

Anyone with an interest in Japan should learn a little Japanese, I
really believe. Daily life is much better when you know a few key
phrases: Hello. My name is. Please. May I? No really, please. Why not?
Oh come on, please. You sure? Last chance. Well fine, be that way. Sorry
for causing a scene. Even if I pay you? No? Hmph, well I didn't want to
anyway.

But when I say "a little" of the language, I mean it. Beyond a handful
of survival sentences, you should give a really good think to whether or
not you want to continue learning Japanese.

So this is Phase II of the Japanese Rule of 7 /Learn Yo' Ass Some
Japanese/ project. Phase I was
[[https://archive.ph/o/wd0m5/www.japaneseruleof7.com/how-to-start-learning-japanese/][here]].
[[https://archive.ph/o/wd0m5/japaneseruleof7.com/how-to-learn-kanji/][Phase III]]?
Well, okay I haven't written that yet. Hey, what can I say, I'm
lazy. Anyway, where were we? Oh yeah, Phase II. The "selection" phase.
For this, you're going to want to find yourself a really tall mountain.
The taller the better, preferably with a sturdy pine tree. Climb to the
mountaintop and sit there. If there is a pine tree, then climb to the
top of that and sit there instead. Then stay there for exactly one week.
You should probably pack some sandwiches, now that I think about it, and
maybe some beers too. Just think how refreshing they'd be. And while
you're there with your pine cones and sandwiches and beer, ask yourself:
Do I really want to study Japanese? No, really. Because here's what it's
all about.

* It's Going to Take Time. A Really Freaking Long Time

I want to tell the world that learning Japanese is easy and fun. Because
that would be great and the world would like that, and then I could sell
the world some secret method that I dreamed up and I'd be rich and the
world would be happy. But on a scale of 1 to
Hot-Tub-at-the-Playboy-Mansion, learning Japanese slots in somewhere
between soldering together your own black-and-white TV and copying the
Bible by hand while wearing a Medieval monk outfit. Plus, it takes a
long time.

Look, everyone thinks they can learn Japanese quickly, fueled in part,
no doubt, by the number of websites claiming to help you do so if you
buy their products. But honestly, when I look at the very few people I
actually know who've succeeded, it's clear why. They got up at 4 a.m.
every morning to do speaking drills, or wrote 50,000 flash cards, or
went to language school five hours a day. Myself, I can honestly say
I've spent at least 4,000 hours actively studying, and that's /not/
counting watching Japanese movies, singing karaoke, having conversations
all day long in Japanese, and working in Japan.

Part of the problem lies with ever-loftier goals. At first, I thought it
would be enough just to master some survival phrases. But every time I
met someone, they asked me questions I couldn't answer. So I learned
more, until I could finally have a conversation. Then I wanted to have a
longer, more interesting conversation, until eventually I realized what
I really needed was to make myself understood in both speech and writing
at roughly the same level I'm at in English. In other words, even
[[https://archive.ph/o/wd0m5/www.japaneseruleof7.com/does-fluency-matter/][fluency]]
wasn't enough. It's a little bit like putting yourself through high
school and college all over again, alone, in Japanese.

If I had to say how long it would take to get reasonably good at
Japanese, I'd estimate a minimum of 3 to 7 years, and possibly much
more, depending upon how much time you devote and how many
[[https://archive.ph/o/wd0m5/www.japaneseruleof7.com/learn-japanese-quickly-in-7-easy-steps/][advantages]]
you bring to the table.

* Safe Return Doubtful

Of the hundreds of people I've seen study Japanese over the years, only
about ten succeeded in speaking the language with any level of
competency. The rest eventually stopped. You might want to give some
thought to undertaking a project with a higher dropout rate than that of
the Navy SEALs. Just saying.

Of course, you can spend the years of your life any way you like, but it
seems a shame to buy a cookbook, go to the store for eggs, flour and a
cake pan, come home and mix up a batter, put it in the oven, and then
half an hour later yank open the oven and throw the whole thing out the
window. In other words, either bake the cake or do not. There is no try.
Pretty sure Yoda said that.

Most people seem to last about a year and a half. They're all balls-out
at the start, and then after several months it dawns on them that it's a
much bigger task than they were led to believe. So be aware of how long
it's going to take. If you want to spend the years, you absolutely can
do it. But think about whether you want to spend a decade on Japanese
before you set out. Doing it halfway seems kind of a waste of time.

* Opportunity Cost

This is a term economists use to make you feel bad about your behavior.
If you spent $10 on a delicious dinner, well, see there Ken, that's $10
you could have invested in the stock market, and now you'd be rich and
could have two delicious dinners. That kind of stuff.

Studying Japanese takes some money, but more importantly, it takes time.
In the 3 to 7 years you spent learning Japanese, you could have learned
to play the guitar, and now you'd be in a cool rock band and getting
lots of sex. Or you could have gone to the gym and now you'd have abs of
steel, and get lots of sex. Or gone back to college and had sex.
Contrary to what you might think, learning Japanese will not help you
have sex in Japan. At least not nearly as much as English will. More on
that in a minute.

* The Payback

I don't like the word "problem." I prefer "challenge." And one of the
challenges---oh the hell with it---the /problem/ with Japanese is that
it's pretty much only useful in Japan. So how long are you going to be
in Japan? Let's say you turn out to be some super prodigy kind of dude
and learn Japanese in just two years. Great, now I hate you. Whatever.
If you stay in Japan for two years, then that's 1:1 and maybe it was
worth the time investment. But what if it takes you five years to learn
and you only stay for a year? See what I'm saying? I've known people who
spent years learning Japanese and watching anime and reading manga and
then once they got here . . . eh, it wasn't as great as they thought
it'd be, and they went home. Open window, insert cake.

* You Really Don't Need Japanese

Of the roughly 20 countries I've been to, Japan is probably the most set
up to accommodate people who don't speak the local language. Many
foreigners live here with no more than a handful of simple phrases and
do just fine. Lots of signs and menus are in English, and the entire
population has received at least six years of English education. Even if
you try to speak Japanese, it may not work. Sometimes no matter how
perfectly you ask a question in Japanese, you'll get an answer in
English, or at least dumbed-down Japanese. Contrary to many countries
that demand you speak the local language, Japan sometimes seems to
prefer you /don't/ speak Japanese.

* Japanese can Make you Less Popular

You know David Blaine, the magician guy? Think about like him at a
party. People see him and they just wig out, like, Wow, David Blaine! Do
some card tricks or hold your breath for ten minutes or something! And
he's like, Nah, I just want to drink a beer like everybody else. That
would suck, right? You'd be like, I went to a party with stupid David
Blaine and he didn't even levitate or anything.

Well that's you in Japan, unless you look super Japanese, and then
people will be confused until they figure out you're secretly white.
Your magic trick is that you can speak English. That's what everyone
wants you to do. And every time you do it, and tell them about how big
the cheeseburgers are back home and how people wear shoes inside the
house, their eyes will light up and they'll be like, Wow, amazing!

And every time you speak Japanese, people will say, "Oh, your Japanese
is so good." And then they'll try to speak English with you. You can say
the most profound thing ever in Japanese, make the funniest joke, talk
about the earth being taken over by space robots, whatever---and all
you'll get back is "Heeeeey." But say any stupid thing off the top of
your head in English and everybody will bust up laughing. English is a
pretty upbeat language; Japanese, eh, not so much. And when it comes to
meeting people of the opposite sex, and potentially even having that
sex, well, they don't want you to be like everybody else. They want the
magic. Just saying.

* Japan Isn't all That

If you came to Japan for a vacation, you probably had a pretty
mind-blowing time. Everything was new, and everything was interesting.
But it was also, in a sense, free, because you used money you'd saved up
or you credit-carded it or something. Either way, you didn't have to
work in Japan in exchange for the experience you were having.

But once you live and work here, that changes. You can go clubbing, take
trips to /onsen/, hang out all night in karaoke booths, but you have to
work in order to make those things possible. And the more fun you want
to have, the more you have to work. That realization changes the
equation. It's not fun for free once you live here.

Now, I like Japan, don't get me wrong. And I like conversing in
Japanese, and reading and writing it. But Japan's still just a place,
with plenty of both good and bad. That's why it's called Japan, and not
Heaven. The architecture---mmm, it's not so great. The natural
scenery---yeah, that's not so great either. The people---ah jeez, well,
you get the idea. But hey, at least the food's good. That's something.

* Choose Wisely

So if you've never wanted to learn Japanese, here's your big chance to
do absolutely butt nothing. On the other hand, if you still really,
really want to study Japanese, and make it a significant part of your
life's work, then I'm 100 percent behind you. Well, maybe like 90, but
that's pretty good anyway. So it's probably safe to come down out of the
tree now and continue on to
[[https://archive.ph/o/wd0m5/japaneseruleof7.com/how-to-learn-kanji/][Phase III]].
I mean, as soon as I write it. Okay, maybe you better stay up
there a bit longer.
