; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32532.0 

	TITLE	D:\my-github\personal-blog-dmytro.zharii.com\articles\2023-06-01-the-value-objects.assets\code-snippets\2023-06-11-the-c-lang-value-object\meters.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_meters_new
PUBLIC	__real@4479c000
EXTRN	_malloc:PROC
EXTRN	__fltused:DWORD
;	COMDAT __real@4479c000
CONST	SEGMENT
__real@4479c000 DD 04479c000r			; 999
CONST	ENDS
_DATA	SEGMENT
$SG9108	DB	'Error: Meter value must be non-negative', 00H
$SG9111	DB	'Error: Meter value must be less than 1000', 00H
_DATA	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_err$1 = -12						; size = 4
_err$2 = -8						; size = 4
_new_meter$ = -4					; size = 4
_value$ = 8						; size = 4
_meters_new PROC
; File D:\my-github\personal-blog-dmytro.zharii.com\articles\2023-06-01-the-value-objects.assets\code-snippets\2023-06-11-the-c-lang-value-object\meters.c
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 5
	push	8
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _new_meter$[ebp], eax
; Line 6
	xorps	xmm0, xmm0
	comiss	xmm0, DWORD PTR _value$[ebp]
	jbe	SHORT $LN2@meters_new
; Line 7
	push	8
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _err$2[ebp], eax
; Line 8
	mov	eax, DWORD PTR _err$2[ebp]
	mov	DWORD PTR [eax], 1
; Line 9
	mov	ecx, DWORD PTR _err$2[ebp]
	mov	DWORD PTR [ecx+4], OFFSET $SG9108
; Line 10
	mov	edx, DWORD PTR _new_meter$[ebp]
	mov	eax, DWORD PTR _err$2[ebp]
	mov	DWORD PTR [edx+4], eax
	jmp	SHORT $LN5@meters_new
$LN2@meters_new:
; Line 11
	movss	xmm0, DWORD PTR _value$[ebp]
	comiss	xmm0, DWORD PTR __real@4479c000
	jbe	SHORT $LN4@meters_new
; Line 12
	push	8
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _err$1[ebp], eax
; Line 13
	mov	ecx, DWORD PTR _err$1[ebp]
	mov	DWORD PTR [ecx], 2
; Line 14
	mov	edx, DWORD PTR _err$1[ebp]
	mov	DWORD PTR [edx+4], OFFSET $SG9111
; Line 15
	mov	eax, DWORD PTR _new_meter$[ebp]
	mov	ecx, DWORD PTR _err$1[ebp]
	mov	DWORD PTR [eax+4], ecx
; Line 16
	jmp	SHORT $LN5@meters_new
$LN4@meters_new:
; Line 18
	mov	edx, DWORD PTR _new_meter$[ebp]
	movss	xmm0, DWORD PTR _value$[ebp]
	movss	DWORD PTR [edx], xmm0
; Line 19
	mov	eax, DWORD PTR _new_meter$[ebp]
	mov	DWORD PTR [eax+4], 0
$LN5@meters_new:
; Line 21
	mov	eax, DWORD PTR _new_meter$[ebp]
; Line 22
	mov	esp, ebp
	pop	ebp
	ret	0
_meters_new ENDP
_TEXT	ENDS
END
